CREATE DATABASE Snow_sale;

USE DATABASE SNOW_SALE;

CREATE SCHEMA sales_schema;

CREATE OR REPLACE WAREHOUSE sales_warehouse
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE STAGE aws_stage
url = 's3://snowfproject1/Sales/';

desc STAGE aws_stage;