USE DATABASE SNOW_SALE;

select * FROM sales_table
LIMIT 3;

-- customer dimension table
CREATE OR REPLACE TABLE dim_customer (
    CUSTOMERID INT,
    CUSTOMERNAME VARCHAR,
    PRIMARY KEY (CUSTOMERID)
);

INSERT INTO dim_customer (CUSTOMERID, CUSTOMERNAME)
SELECT DISTINCT CUSTOMERID, CUSTOMERNAME
FROM sales_table;

SELECT * FROM dim_customer
LIMIT 5;


CREATE OR REPLACE TABLE dim_orders (
    ORDERID INT,
    QUANTITY INT,
    PRIMARY KEY (ORDERID)
);

INSERT INTO dim_orders (ORDERID, QUANTITY)
SELECT DISTINCT ORDERID, QUANTITY 
FROM sales_table;

SELECT * FROM dim_orders
LIMIT 3;

CREATE OR REPLACE TABLE dim_products (
    PRODUCTID INT,
    PRODUCTNAME VARCHAR,
    PRIMARY KEY (PRODUCTID)
);

INSERT INTO dim_products (PRODUCTID, PRODUCTNAME)
SELECT DISTINCT PRODUCTID, PRODUCTNAME
FROM sales_table;

SELECT * FROM dim_products
LIMIT 3;

CREATE OR REPLACE TABLE dim_date (
    DATEID INT AUTOINCREMENT,
    date DATE,
    DAY INT,
    MONTH INT,
    YEAR INT,
    PRIMARY KEY (DATEID)
);

INSERT INTO dim_date (date, DAY, MONTH, YEAR)
SELECT DISTINCT ORDERDATE,
DAY(ORDERDATE),
MONTH(ORDERDATE),
YEAR(ORDERDATE)
FROM sales_table;

SELECT * FROM dim_date
LIMIT 5;

-- creating a fact table
CREATE OR REPLACE TABLE sales_fact (
    sales_id INT AUTOINCREMENT,
    CUSTOMERID INT,
    ORDERID INT,
    PRODUCTID INT,
    DATEID INT,
    PRICEPERUNIT DECIMAL (10, 2),
    TOTALPRICE DECIMAL (10, 2),
    PRIMARY KEY (sales_id),
    FOREIGN KEY (CUSTOMERID) REFERENCES dim_customer(CUSTOMERID),
    FOREIGN KEY (ORDERID) REFERENCES dim_orders(ORDERID),
    FOREIGN KEY (PRODUCTID) REFERENCES dim_products(PRODUCTID),
    FOREIGN KEY (DATEID) REFERENCES dim_date(DATEID)
);

INSERT INTO sales_fact (CUSTOMERID, ORDERID, PRODUCTID, DATEID, PRICEPERUNIT, TOTALPRICE)
SELECT
    c.CUSTOMERID,
    o.ORDERID,
    p.PRODUCTID,
    d.DATEID,
    s.PRICEPERUNIT,
    s.TOTALPRICE
FROM sales_table s
LEFT JOIN dim_customer c ON s.CUSTOMERNAME = c.CUSTOMERNAME
LEFT JOIN dim_orders o ON s.QUANTITY = o.QUANTITY
LEFT JOIN dim_products p ON s.PRODUCTNAME = p.PRODUCTNAME
LEFT JOIN dim_date d ON s.ORDERDATE = d.date;

SELECT * FROM sales_fact
LIMIT 3;