USE DATABASE SNOW_SALE;

select * FROM sales_table
LIMIT 3;

-- customer dimension table
CREATE OR REPLACE TABLE dim_customer (
    CUSTOMERID INT,
    CUSTOMERNAME VARCHAR,
    PRIMARY KEY (CUSTOMERID)
);

INSERT INTO dim_customer (CUSTOMERID, CUSTOMERNAME)
SELECT DISTINCT CUSTOMERID, CUSTOMERNAME
FROM sales_table;

SELECT * FROM dim_customer
LIMIT 5;


CREATE OR REPLACE TABLE dim_orders (
    ORDERID INT,
    QUANTITY INT,
    PRIMARY KEY (ORDERID)
);

INSERT INTO dim_orders (ORDERID, QUANTITY)
SELECT DISTINCT ORDERID, QUANTITY 
FROM sales_table;

SELECT * FROM dim_orders
LIMIT 3;

CREATE OR REPLACE TABLE dim_products (
    PRODUCTID INT,
    PRODUCTNAME VARCHAR,
    PRIMARY KEY (PRODUCTID)
);

INSERT INTO dim_products (PRODUCTID, PRODUCTNAME)
SELECT DISTINCT PRODUCTID, PRODUCTNAME
FROM sales_table;

SELECT * FROM dim_products
LIMIT 3;

CREATE OR REPLACE TABLE dim_date (
    DATEID INT AUTOINCREMENT,
    date DATE,
    DAY INT,
    MONTH INT,
    YEAR INT,
    PRIMARY KEY (DATEID)
);

INSERT INTO dim_date (date, DAY, MONTH, YEAR)
SELECT DISTINCT ORDERDATE,
DAY(ORDERDATE),
MONTH(ORDERDATE),
YEAR(ORDERDATE)
FROM sales_table;

SELECT * FROM dim_date
LIMIT 5;